<?php
class MySQL
{
    private 
            $stmt = null,
            $DB = null;
    
    public function __construct($DB, $errorText="")
    {
        $this->DB = $DB;
    }
    
    public function prepare ($sql, array $parameters = null)
    {
        $this->stmt = $this->DB->prepare($sql);
        if(!is_null($parameters)) {
            foreach($parameters as $key => $val) {
                $this->stmt->bindParam($key, $val);
                $this->DB->execute();
            }
        }
    }
    public function bind (array $parameters)
    {
        foreach($parameters as $key => $val) {
            $this->stmt->bindParam($key, $val);
            $this->DB->execute();
        }   
    }
    public function execute ()
    {
        if(!$this->DB->execute()) {
            throw new Exception("SQL-error, generated by queryWithExceptions-function in ".__CLASS__.PHP_EOL." Error explanation:,".$explanation.PHP_EOL." Error from queryWithExceptions-function in KIRJASTODB-class. The exact query in question: ".$sql.PHP_EOL." debug_backtrace: ".debug_backtrace());
        }
    }
    
    public static function filterVariable($value)
    {
        if(empty($value))
            return "";
        // Stripslashes
        if (get_magic_quotes_gpc()) {
            $value = stripslashes($value);
        }
        if($value == '') {
            $value = 'NULL';
        } elseif (is_string($value) || is_numeric($value) || is_bool($value) || $value[0] == '0') {
            $value = $this->real_escape_string($value);
        } else { // If there is problem with the value, we have to cause an error for this, otherwise it's hard ro debug!
            var_dump(debug_backtrace());
            throw new Exception("Problem in ".__CLASS__." real_escape_string should get string-parameter, something else was given. Value given". print_r($value, true));
        }
        return $value;
    }
}
?>
